### ISSUE TITLE
Erro Registro0001 EFD Contribuições

### ISSUE THREAD

**Issue by leandrossantos** [orochasamuel/fiscalbr.net#39]
Estou montando script para gerar arquivo SPED Fiscal e Contribuições, o Fiscal já está 100% mais no Contribuições estou com um problema que não consegui descobrir o porque, vejam a imagem abaixo e se alguém souber como resolver ficarei grato.

![Screenshot_338](https://user-images.githubusercontent.com/6373944/124854446-ba092680-df7d-11eb-8846-a21c9de6c506.png)

**Comment by orochasamuel** [comment]
Fala @leandrossantos tudo na paz?

Isso tá com cara de ser "paranoia" do VS, no VS Code acontece umas paradas assim de vez em quando.

Dá um reload na solution e vê se resolve.

Vida longa e próspera. 🖖

**Comment by leandrossantos** [comment]
> Fala @leandrossantos tudo na paz?
> 
> Isso tá com cara de ser "paranoia" do VS, no VS Code acontece umas paradas assim de vez em quando.
> 
> Dá um reload no projeto e vê se resolve.
> 
> Você está usando pelo Nuget ou DLL?
> 
> Vida longa e próspera. 🖖

Oi @orochasamuel sim já tentei várias vezes e nada.

**Comment by leandrossantos** [comment]
> Fala @leandrossantos tudo na paz?
> 
> Isso tá com cara de ser "paranoia" do VS, no VS Code acontece umas paradas assim de vez em quando.
> 
> Dá um reload no projeto e vê se resolve.
> 
> Você está usando pelo Nuget ou DLL?
> 
> Vida longa e próspera. 🖖

@orochasamuel fiz os testes usando DLL e Nuget e nos dois casos acontece o erro :/

**Comment by orochasamuel** [comment]
@leandrossantos qual a versão do .NET Framework do seu projeto?

Ontem eu testei criar um novo projeto com 4.8, 4.7.2, 4.6, 4.5.2 e 5, fiz a instalação pelo Nuget e funcionou normal.

Tentou desinstalar o pacote Nuget e instalar novamente?

Vida longa e próspera. 🖖

**Comment by leandrossantos** [comment]
> @leandrossantos qual a versão do .NET Framework do seu projeto?
> 
> Ontem eu testei criar um novo projeto com 4.8, 4.7.2, 4.6, 4.5.2 e 5, fiz a instalação pelo Nuget e funcionou normal.
> 
> Tentou desinstalar o pacote Nuget e instalar novamente?
> 
> Vida longa e próspera. 🖖

Mexi mais um pouco aqui e mudei a posição das declarações e então deu certo, o erro sumiu.
Valeu ai.
