### ISSUE TITLE
Classe Registro90 do SINTEGRA incompleta no nuget

### ISSUE THREAD

**Issue by andersonbrv** [orochasamuel/fiscalbr.net#40]
A classe Registro90 do SINTEGRA está implementada no github, mas na biblioteca que está no nuget não.

**Comment by orochasamuel** [comment]
Fala @andersonbrv tudo na paz?

A geração do Registro90 é diferente dos demais. As propriedades estão definidas como `private`.

![image](https://user-images.githubusercontent.com/15462690/126205969-0384c833-8806-4b0d-aa70-1bd077368f47.png)

Utilize o construtor do `Registro90` para efetuar a geração de linhas.

Vida longa e próspera. 🖖

**Comment by andersonbrv** [comment]
Obrigado!
