### ISSUE TITLE
Como se cria um arquivo Sped pelo nuget?

### ISSUE THREAD

**Issue by kailonalexandre** [orochasamuel/fiscalbr.net#41]
Boa tarde! Sou novo por aqui e estou desenvolvendo uma implementação num sistema onde eu teria que gerar um arquivo Sped, porém não entendi muito bem a documentação disponibilizada e fiquei com algumas duvidas na hora de criar!

Eu iniciei dessa forma:

![image](https://user-images.githubusercontent.com/41274609/140981394-8c3a9511-aaec-4393-8525-19a63154c803.png)
 
Eu pego as informações necessárias e adiciono nas linhas e no fim do método eu crio o txt com essas informações.

![image](https://user-images.githubusercontent.com/41274609/140981559-76bb5d27-8097-40f7-8376-e1e263279df7.png)

porém não entendi o método escrever campos! 

Caso eu esteja iniciando de forma incorreta por favor eu peço q me passem uma orientação de como começar! 

agradeço desde já!

**Comment by orochasamuel** [comment]
Fala @kailonalexandre

Você pode escrever registro a registro e ir gerando as linhas **OU** pode inserir as informações direto no `ArquivoEFDFiscal` e depois gerar todas as linhas de uma vez.

```csharp

            var reg0000 = new EFDFiscal.Bloco0.Registro0000
            {
                CodVer = Common.CodigoVersaoLeiaute.V15,
                CodFin = Common.IndCodFinalidadeArquivo.RemessaArquivoOriginal,
                DtIni = initialDate,
                DtFin = finalDate,
                Nome = "BANCO DO BRASIL S.A.",
                Cnpj = "00000000000191",
                Uf = "GO",
                Ie = "123456789",
                CodMun = "5204508",
                IndPerfil = Common.IndPerfilArquivo.A,
                IndAtiv = Common.IndTipoAtividade.Outros
            };

            var linhaGerada = Common.Sped.EscreverCamposSped.EscreverCampos(reg0000);

```
---

```csharp

            var sped = new ArquivoEFDFiscal();

            if (sped.Bloco0 is null)
                sped.Bloco0 = new FiscalBr.EFDFiscal.Bloco0();

            var reg0000 = new EFDFiscal.Bloco0.Registro0000
            {
                CodVer = Common.CodigoVersaoLeiaute.V15,
                CodFin = Common.IndCodFinalidadeArquivo.RemessaArquivoOriginal,
                DtIni = initialDate,
                DtFin = finalDate,
                Nome = "BANCO DO BRASIL S.A.",
                Cnpj = "00000000000191",
                Uf = "GO",
                Ie = "123456789",
                CodMun = "5204508",
                IndPerfil = Common.IndPerfilArquivo.A,
                IndAtiv = Common.IndTipoAtividade.Outros
            };

            sped.Bloco0.Reg0000 = reg0000;

            sped.GerarLinhas();

            sped.Escrever(@"C:\Users\orochasamuel\Documents\fiscalbr-test.txt");

```

PS: O método `GerarLinhas()` só deve ser utilizado uma única vez logo após popular os registros com as informações do seu sistema.

Vida longa e próspera 🖖

**Comment by kailonalexandre** [comment]
Opa,  orochasamuel, Muitissimo obrigado!!!  Já me ajudou muito! Quaisquer duvidas retornarei por aqui.
